import React, { useMemo, useState } from 'react';
import Pagination from '../DutyHoursReport/Pagination.jsx';
import TimelineBar from './TimelineBar.jsx';

const AdminDutyHoursTable = ({ sessions, isLoading, onDayAction, onDeleteSession }) => {
  const [currentPage, setCurrentPage] = useState(1);
  const [showUpdateDetails, setShowUpdateDetails] = useState(null);
  const rowsPerPage = 10;

  // Process sessions into table data
  const tableData = useMemo(() => {
    console.log('Processing sessions into table data...');
    
    if (!sessions || sessions.length === 0) {
      console.log('No sessions to process');
      return [];
    }

    const workSessions = sessions.filter(session => session.session_type === 'work');
    console.log('Work sessions after filtering:', workSessions.length);
    
    // Group ALL sessions (work + break) by user and date for timeline
    const allSessionsGrouped = sessions.reduce((groups, session) => {
      const userKey = session.user_id;
      const dateKey = `${userKey}-${session.date}`;
      
      if (!groups[dateKey]) {
        groups[dateKey] = {
          userName: session.username || `User ${session.user_id}`,
          userId: session.user_id,
          date: session.date,
          allSessions: [] // All sessions for timeline
        };
      }
      groups[dateKey].allSessions.push(session);
      return groups;
    }, {});
    
    // Group work sessions for pairs calculation
    const groupedByUserAndDate = workSessions.reduce((groups, session) => {
      const userKey = session.user_id;
      const dateKey = `${userKey}-${session.date}`;
      
      if (!groups[dateKey]) {
        groups[dateKey] = {
          userName: session.username || `User ${session.user_id}`,
          userId: session.user_id,
          date: session.date,
          sessions: []
        };
      }
      groups[dateKey].sessions.push(session);
      return groups;
    }, {});

    console.log('Grouped data:', Object.keys(groupedByUserAndDate).length, 'groups');
    
    // Process each group to create pairs
    const processedData = Object.values(groupedByUserAndDate).map(group => {
      const sortedSessions = group.sessions.sort((a, b) => {
        // Sort by time strings (HH:MM:SS)
        return a.in_time.localeCompare(b.in_time);
      });

      let pairs = [];
      let totalHours = 0;
      let hasUpdatedSessions = false;
      let updateDetails = [];

      for (let i = 0; i < sortedSessions.length; i++) {
        const session = sortedSessions[i];
        
        const pair = {
          inTime: session.in_time,
          outTime: session.out_time,
          sessionId: session.id,
          autoGenerated: session.auto_generated === 1,
          updater: session.updater_username ? {
            username: session.updater_username,
            updatedAt: session.updated_at
          } : null
        };

        pairs.push(pair);

        // Collect update information
        if (!pair.autoGenerated && pair.updater) {
          hasUpdatedSessions = true;
          updateDetails.push({
            sessionIndex: i + 1,
            updater: pair.updater.username,
            updatedAt: new Date(pair.updater.updatedAt),
            autoGenerated: pair.autoGenerated,
            inTime: pair.inTime,
            outTime: pair.outTime
          });
        }

        // Calculate duration from time strings
        if (pair.inTime && pair.outTime) {
          const inTime = pair.inTime.split(':').map(Number);
          const outTime = pair.outTime.split(':').map(Number);
          
          const inMinutes = inTime[0] * 60 + inTime[1] + (inTime[2] / 60);
          const outMinutes = outTime[0] * 60 + outTime[1] + (outTime[2] / 60);
          
          const hours = (outMinutes - inMinutes) / 60;
          totalHours += hours;
        }
      }

      // Format date as dd/mm/yyyy
      const dateObj = new Date(group.date);
      const day = String(dateObj.getDate()).padStart(2, '0');
      const month = String(dateObj.getMonth() + 1).padStart(2, '0');
      const year = dateObj.getFullYear();
      const formattedDate = `${day}/${month}/${year}`;

      const dayName = dateObj.toLocaleDateString('en-US', { weekday: 'short' });

      // Get all sessions (work + break) for this day from the allSessionsGrouped
      const dateKey = `${group.userId}-${group.date}`;
      const allSessionsForDay = allSessionsGrouped[dateKey]?.allSessions || [];

      return {
        userName: group.userName,
        date: formattedDate,
        dayName: dayName,
        pairs,
        sessions: group.sessions, // Work sessions only
        allSessions: allSessionsForDay, // All sessions (work + break) for timeline
        totalHours: totalHours.toFixed(2),
        rawDate: group.date,
        userId: group.userId,
        hasUpdatedSessions,
        updateDetails
      };
    });

    console.log('Processed table data:', processedData);
    return processedData;
  }, [sessions]);

  // Format time display (convert 24h to 12h format)
  const formatTimeDisplay = (timeString) => {
    if (!timeString || timeString === 'NULL') return 'NULL';
    
    const [hours, minutes, seconds] = timeString.split(':');
    let hourNum = parseInt(hours);
    const period = hourNum >= 12 ? 'PM' : 'AM';
    
    hourNum = hourNum % 12;
    hourNum = hourNum ? hourNum : 12;
    
    return `${hourNum}:${minutes}:${seconds} ${period}`;
  };

  // Rest of the component remains the same...
  const sortedTableData = useMemo(() => {
    return tableData.sort((a, b) => new Date(a.rawDate) - new Date(b.rawDate));
  }, [tableData]);

  const totalPages = Math.ceil(sortedTableData.length / rowsPerPage);
  const currentData = sortedTableData.slice(
    (currentPage - 1) * rowsPerPage,
    currentPage * rowsPerPage
  );


  const formatUpdateTime = (date) => {
    if (!date) return '';
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const UpdateDetailsModal = ({ dayData, onClose }) => {
    if (!dayData) return null;

    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-gray-800 rounded-2xl p-6 w-full max-w-2xl border border-gray-700/50">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold">Update History</h2>
            <button onClick={onClose} className="text-gray-400 hover:text-white text-xl">✕</button>
          </div>
          
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2">{dayData.userName} - {dayData.date}</h3>
            <p className="text-gray-400">Manually updated sessions</p>
          </div>

          <div className="space-y-4 max-h-96 overflow-y-auto">
            {dayData.updateDetails.map((update, index) => (
              <div key={index} className="bg-gray-700/30 rounded-lg p-4 border border-orange-500/20">
                <div className="flex justify-between items-start mb-3">
                  <div>
                    <span className="font-semibold text-orange-400">Duration {update.sessionIndex}</span>
                    <div className="text-sm text-gray-300 mt-1">
                      {formatTimeDisplay(update.inTime)} - {formatTimeDisplay(update.outTime)}
                    </div>
                  </div>
                  <span className="px-2 py-1 bg-orange-500/20 text-orange-400 text-xs rounded-full">
                    Manual
                  </span>
                </div>
                
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-400">Updated by:</span>
                    <div className="text-white font-medium">{update.updater}</div>
                  </div>
                  <div>
                    <span className="text-gray-400">Updated at:</span>
                    <div className="text-white">{formatUpdateTime(update.updatedAt)}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="flex justify-end mt-6">
            <button
              onClick={onClose}
              className="bg-gray-700 hover:bg-gray-600 text-white px-6 py-2 rounded-lg font-semibold transition-colors duration-200"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    );
  };

  if (isLoading) {
    return (
      <div className="text-center py-12">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto"></div>
        <p className="mt-4 text-gray-400">Loading duty hours...</p>
      </div>
    );
  }

  if (sessions.length === 0) {
    return (
      <div className="text-center py-12 text-gray-400">
        <div className="text-6xl mb-4">📊</div>
        <h3 className="text-xl font-semibold mb-2">No sessions found</h3>
        <p>No duty hours recorded for the selected date range</p>
        <div className="mt-4 text-sm">
          <p>Total sessions in database: {sessions.length}</p>
          <p>Try selecting a different date range or employee</p>
        </div>
      </div>
    );
  }

  if (tableData.length === 0) {
    return (
      <div className="text-center py-12 text-yellow-400">
        <div className="text-6xl mb-4">⚠️</div>
        <h3 className="text-xl font-semibold mb-2">Data Processing Issue</h3>
        <p>Sessions were fetched but couldn't be processed into table format</p>
        <div className="mt-4 text-sm">
          <p>Sessions received: {sessions.length}</p>
          <p>Table data: {tableData.length}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gray-800/50 rounded-2xl p-6 border border-gray-700/50">
      <div className="mb-4 p-4 bg-blue-500/10 rounded-lg">
        <div className="text-sm text-blue-300">
          Showing {tableData.length} days with sessions • {sessions.length} total sessions
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full min-w-max">
          <thead>
            <tr className="border-b border-gray-600">
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap">User Name</th>
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap">Date</th>
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap">Day</th>
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap min-w-[800px]">24-Hour Timeline</th>
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap">Total Hours</th>
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap">Updates</th>
              <th className="text-left py-3 px-4 font-semibold text-gray-300 whitespace-nowrap">Actions</th>
            </tr>
          </thead>
          <tbody>
            {currentData.map((row, index) => (              
              <tr 
                key={`${row.userId}-${row.rawDate}`} 
                className={`border-b border-gray-700/50 ${
                  index % 2 === 0 ? 'bg-gray-700/20' : 'bg-gray-800/20'
                } hover:bg-gray-700/30 transition-colors`}
              >
                <td className="py-3 px-4 text-white whitespace-nowrap">{row.userName}</td>
                <td className="py-3 px-4 text-gray-300 whitespace-nowrap">{row.date}</td>
                <td className="py-3 px-4 text-gray-300 whitespace-nowrap">{row.dayName}</td>
                
                {/* Timeline Visualization - Shows all sessions (work + break) */}
                <td className="py-3 px-4 min-w-0">
                  <TimelineBar sessions={row.allSessions || []} date={row.rawDate} />
                </td>
                
                <td className="py-3 px-4 font-semibold text-blue-300 whitespace-nowrap">
                  {row.totalHours}h
                </td>
                
                <td className="py-3 px-4">
                  {row.hasUpdatedSessions ? (
                    <button
                      onClick={() => setShowUpdateDetails(row)}
                      className="text-orange-400 hover:text-orange-300 px-3 py-1 rounded-lg border border-orange-500/50 hover:bg-orange-500/10 transition-colors flex items-center gap-2 text-sm"
                      title="View update history"
                    >
                      <span className="w-2 h-2 bg-orange-500 rounded-full"></span>
                      Details
                    </button>
                  ) : (
                    <span className="text-green-400 text-sm px-3 py-1 rounded-lg border border-green-500/30 bg-green-500/10">
                      Auto
                    </span>
                  )}
                </td>
                
                <td className="py-3 px-4">
                  <button
                    onClick={() => onDayAction(row)}
                    className="text-gray-400 hover:text-white p-2 hover:bg-gray-600/50 rounded transition-colors"
                    title="Manage Sessions"
                  >
                    ⋮
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {totalPages > 1 && (
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={setCurrentPage}
        />
      )}

      {showUpdateDetails && (
        <UpdateDetailsModal 
          dayData={showUpdateDetails} 
          onClose={() => setShowUpdateDetails(null)} 
        />
      )}
    </div>
  );
};

export default AdminDutyHoursTable;